# SMART Website Continuous Deployment (CD) Workflow
# ================================================
#
# Author: Akshay Mestry <xa@mes3.dev>
# Created on: 26 August, 2025
# Last updated on: 13 October, 2025

name: Continuous Deployment
run-name: Started ${{ github.workflow }} (CD) workflow

on:
  workflow_dispatch:
    inputs:
      deploy_target:
        description: "Deployment environment"
        required: false
        default: "production"

env:
  ARTIFACT_NAME: smart-pages
  OUTPUT_DIR: docs/build/
  SOURCE_DIR: docs/source/
  PYTHON_VERSION: "3.13.2"
  DOCSEARCH_APP_ID: ${{ secrets.DOCSEARCH_APP_ID }}
  DOCSEARCH_API_KEY: ${{ secrets.DOCSEARCH_API_KEY }}
  DOCSEARCH_INDEX_NAME: ${{ secrets.DOCSEARCH_INDEX_NAME }}

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build website pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install documentation dependencies
        run: python -m pip install -Uq -e .
      - name: Build HTML pages with Sphinx
        run: sphinx-build --builder dirhtml --fail-on-warning --show-traceback --fresh-env --write-all --quiet $SOURCE_DIR $OUTPUT_DIR
      - name: Upload built documentation as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.OUTPUT_DIR }}

  deploy:
    name: Deploy built website
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: production
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: ${{ env.ARTIFACT_NAME }}
